laurel_sprout: Add missing FCM entries
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.power@1.3::IPower/default
    android.hardware.light@2.0::ILight/default