laurel_sprout: fix FCM
The following HALs in device manifest are not declared in FCM <= level 5:
  android.hardware.power.IPower/default (@3)
ERROR: files are incompatible: android.hardware.light@2.0::ILight/default is deprecated in compatibility matrix at FCM Version 5; it should not be served.
    because it matches android.hardware.light@2.0::ILight/default from /system/etc/vintf/compatibility_matrix.4.xml: Success
INCOMPATIBLE